
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 20 22:40:43 BRST 2016
//----------------------------------------------------

package lua;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int TWO_DOTS = 37;
  public static final int FUNCTION = 15;
  public static final int L_PARENTHESIS = 25;
  public static final int REPEAT = 6;
  public static final int SMALLER_THAN_OR_EQUAL = 39;
  public static final int FOR = 12;
  public static final int MINUS = 32;
  public static final int GREATER_THAN = 40;
  public static final int R_PARENTHESIS = 26;
  public static final int SEMICOLON = 50;
  public static final int NOT = 46;
  public static final int AND = 44;
  public static final int ELSEIF = 10;
  public static final int L_BRACES = 27;
  public static final int NIL = 21;
  public static final int L_BRACKETS = 29;
  public static final int OR = 45;
  public static final int IN = 14;
  public static final int COMMA = 13;
  public static final int DIV = 34;
  public static final int UNTIL = 7;
  public static final int PLUS = 31;
  public static final int IF = 8;
  public static final int EXP = 35;
  public static final int DOT = 19;
  public static final int EOF = 0;
  public static final int RETURN = 17;
  public static final int EQUAL = 2;
  public static final int TRUE = 23;
  public static final int UOP = 51;
  public static final int error = 1;
  public static final int R_BRACKETS = 30;
  public static final int NUMBER = 52;
  public static final int MOD = 36;
  public static final int BREAK = 18;
  public static final int NAME = 49;
  public static final int TIMES = 33;
  public static final int COLON = 20;
  public static final int ELSE = 11;
  public static final int SMALLER_THAN = 38;
  public static final int WHILE = 5;
  public static final int THREE_DOTS = 24;
  public static final int R_BRACES = 28;
  public static final int THEN = 9;
  public static final int END = 4;
  public static final int APROX = 43;
  public static final int STRING = 48;
  public static final int LOCAL = 16;
  public static final int HASHTAG = 47;
  public static final int GREATER_THAN_OR_EQUAL = 41;
  public static final int FALSE = 22;
  public static final int EQUAL_EQUAL = 42;
  public static final int DO = 3;
}

