
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 18 01:20:51 BRST 2016
//----------------------------------------------------

package sample;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int MINUS = 3;
  public static final int NUMBER = 8;
  public static final int L_PARENTHESIS = 6;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int DIV = 4;
  public static final int error = 1;
  public static final int TIMES = 5;
  public static final int R_PARENTHESIS = 7;
}

